# Generated by Django 3.1.2 on 2022-09-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='tipo_manteniento',
            new_name='tipo_mantenimiento',
        ),
    ]
