# Generated by Django 3.1.2 on 2022-09-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='proximo_mantenimiento',
            field=models.DateField(),
        ),
    ]
