# Generated by Django 3.1.2 on 2022-09-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220915_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_mantenimiento',
            field=models.DateField(auto_now_add=True),
        ),
    ]
